name: Run tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      id: check-out-code
      uses: actions/checkout@v2

    - name: Install packages and run tests
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm run test
